### PR TITLE
Added Romanian (ro) localization

### PR DESCRIPTION
**Pull request by lainefox**
Translated the app into Romanian.

My first pull request... I hope I am doing this right.

### CODE REVIEW

**Comment by danilkinkin** [comment]
Looks good, I'll try to merge the code as soon as possible and fix issues if I find it.

Thanks a lot for your work

**Comment by danilkinkin** [comment]
Hi @lainefox, I have few questions, can you help?
It's correct translations?
```
<string name="wallet_title">Budget</string>
<string name="label_budget">Budget</string>
<string name="total_title">Total</string>
```

Also, about plural forms. Can you provide plural form `few`
key `one` applies for value `1`
key `few` applies for values `0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19`
key `other` applies for values `20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32...`
```
<plurals name="spends_today">
    <item quantity="one">%1$s cheltuit azi</item>
    <item quantity="few"></item>
    <item quantity="other">%1$s cheltuiți azi</item>
</plurals>
<plurals name="day">
    <item quantity="one">o zi</item>
    <item quantity="few"></item>
    <item quantity="other">%1$s zile</item>
</plurals>
<plurals name="finish_date_label">
    <item quantity="one">Până pe %1$s (o zi)</item>
    <item quantity="few"></item>
    <item quantity="other">Până pe %1$s (%2$s zile)</item>
</plurals>
<plurals name="finish_date">
    <item quantity="one">%1$s (o zi)</item>
    <item quantity="few"></item>
    <item quantity="other">%1$s (%2$s zile)</item>
</plurals>
```

**Comment by lainefox** [comment]
> It's correct translations?
Oh, sry, it should've been _"Buget"_ instead of _"Budget"_. _"Total"_ is correct the way it is.
```
<string name="wallet_title">Buget</string>
<string name="label_budget">Buget</string>
<string name="total_title">Total</string>
```

---

> Also, about plural forms. Can you provide plural form few
Yeah, the form used for `other` applies to `few` too in Romanian, so here's the final version:
```
<plurals name="spends_today">
    <item quantity="one">%1$s cheltuit azi</item>
    <item quantity="few">%1$s cheltuiți azi</item>
    <item quantity="other">%1$s cheltuiți azi</item>
</plurals>
<plurals name="day">
    <item quantity="one">o zi</item>
    <item quantity="few">%1$s zile</item>
    <item quantity="other">%1$s zile</item>
</plurals>
<plurals name="finish_date_label">
    <item quantity="one">Până pe %1$s (o zi)</item>
    <item quantity="few">Până pe %1$s (%2$s zile)</item>
    <item quantity="other">Până pe %1$s (%2$s zile)</item>
</plurals>
<plurals name="finish_date">
    <item quantity="one">%1$s (o zi)</item>
    <item quantity="few">%1$s (%2$s zile)</item>
    <item quantity="other">%1$s (%2$s zile)</item>
</plurals>
```

Sorry for the delay...

**Comment by danilkinkin** [comment]
Thanks

**Comment by danilkinkin** [comment]
Added in release [v.3.11.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.11.0)

**Pull request merged**
